services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=filebrowser"
    ports:
      - "192.168.42.1:8086:80"
    volumes:
      - /srv:/srv
      - /home/kyriakosp/Documents:/srv/Documents
      - /srv/filebrowser/database:/database
    environment:
      - FB_NOAUTH=true
    restart: unless-stopped
