services:
  tileserver:
    image: maptiler/tileserver-gl:latest
    container_name: tileserver
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=maps"
    ports:
      - "192.168.42.1:8083:8080"
    volumes:
      - /srv/maps/data:/data:ro
      - /srv/maps/styles:/styles:ro
      - /srv/maps/config.json:/config.json:ro
    command: -c /config.json
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-maps
    labels:
      - "com.centurylinklabs.watchtower.scope=maps"
    command:
      - --scope=maps
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_POLL_INTERVAL=86400
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
