services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    environment:
      - LT_UPDATE_MODELS=true
      - LT_DISABLE_WEB_UI=false
    volumes:
      - /srv/libretranslate/data:/home/libretranslate/.local
    ports:
      - "192.168.42.1:8095:5000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
